image: maven:3.9.1-eclipse-temurin-17-alpine

stages:
  - build
  - test
  - visualize
  - deploy_reports

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  coverage: '\d+.\d+ \% covered'
  script:
    - mvn clean
    - mvn org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report
    - mvn test-compile org.pitest:pitest-maven:mutationCoverage
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/",
      instructions, "instructions covered"; print 100*covered/instructions, "%
      covered" }' target/site/jacoco/jacoco.csv
  artifacts:
    paths:
      - target/site/
      - target/pit-reports/

pages:
  stage: deploy_reports
  dependencies:
    - test
  script:
    - mkdir -p public/jacoco
    - mv target/site/jacoco public/
    - mv target/pit-reports public/
  artifacts:
    paths:
      - public