image: maven:3.9.1-eclipse-temurin-17-alpine

stages:
  - build
  - test
  - deploy_reports

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn clean
    - mvn test

deploy_reports:
  stage: deploy_reports
  script:
    - echo "TODO"