version: "3.9"
services:

  testing-application:
    container_name: "st-testing-application"
    build: .
    ports:
      - "8080:8080"


  prometheus:
    container_name: "st-prometheus"
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: alertmanager/rules/
        target: /etc/prometheus/alertmanager/rules/


  grafana:
    container_name: "st-grafana"
    image: 'grafana/grafana'
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

  alert-manager:
    container_name: "st-alert-manager"
    image: "prom/alertmanager"
    ports:
      - "9093:9093"
    volumes:
      - type: bind
        source: alertmanager/config.yml
        target: /etc/alertmanager/alertmanager.yml


volumes:
  grafana_data: { }