version: "3.9"
services:

  testing-application:
    container_name: "st-testing-application"
    build: .
    ports:
      - "8080:8080"


  prometheus:
    container_name: "st-prometheus"
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: prometheus.yml
        target: /etc/prometheus/prometheus.yml

