{
 "title": "Software Testing",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes)*100/sum(jvm_memory_max_bytes)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_usage*100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total JVM Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes)/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Used Disk Space (overall)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(disk_total_bytes - disk_free_bytes)/disk_total_bytes*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(system_cpu_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Starttime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"spring-boot-st\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Customers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "customer_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Errors/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[1m]))",
     "legendFormat": "Status 5xx"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"4..\"}[1m]))",
     "legendFormat": "Status 4xx"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{exception!=\"None\"}[1m]))",
     "legendFormat": "Exceptions"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "increase(logback_events_total[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri!=\"/actuator\", uri!=\"/actuator/prometheus\"}[1m])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(http_server_requests_seconds_max{uri!=\"/actuator\", uri!=\"/actuator/prometheus\"}[2m])",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}