groups:
  - name: default
    rules:
      - alert: RequestRate
        expr: rate(http_server_requests_seconds_count{status=~"5.."}[1m]) > 0
        for: 1m
        annotations:
          summary: 'server error caught'
        labels:
          severity: 'critical'